joelshepherd/tabliss

scripts/translationRunner.js
src/app/settings/System.tsx
src/locales/lang/de.json
src/locales/lang/whitelist_de.json
src/locales/locales.ts

Love the extension. Opening a new browser tab is suddenly so much more enjoyable :relaxed:

Add German translation

---

src/plugins/widgets/search/engines.json

Startpage is a privacy focused search engine.

Added Startpage search engine.

---

.gitignore
src/plugins/widgets/search/SearchSettings.tsx

Searches in drop down

---

src/locales/lang/cs.json

Minor change to Czech translation to correspond with vocabularies used by web browsers.
Original translation is fine, this change is just aesthetic.

Minor change to Czech translation

---

src/app/dashboard/Dashboard.sass
src/plugins/backgrounds/unsplash/Unsplash.sass
src/plugins/backgrounds/unsplash/Unsplash.tsx
src/plugins/backgrounds/unsplash/UnsplashSettings.tsx
src/plugins/backgrounds/unsplash/constants.ts
src/plugins/backgrounds/unsplash/interfaces.ts

Added option to blur the Unsplash background image, as requested in #71.

Adding option to blur the background image

---

src/plugins/widgets/literature-clock/LiteratureClock.sass
src/plugins/widgets/literature-clock/LiteratureClock.tsx
src/plugins/widgets/literature-clock/LiteratureClockSettings.tsx
src/plugins/widgets/literature-clock/index.ts
src/plugins/widgets/register.ts

Clock using time quotes from the literature, based on work and idea by
[Jaap Meijers](http://www.eerlijkemedia.nl/) ([E-reader clock](https://www.instructables.com/id/Literary-Clock-Made-From-E-reader/)).

Add "Literature Clock" widget

---

src/locales/lang/nl.json

* Change "Nieuw Tabblad" into "Nieuw tabblad"
* Change "content" into "inhoud"

Dutch locale - Change "Nieuw Tabblad" into "Nieuw tabblad"

---

src/plugins/widgets/quote/Quote.tsx

Add quotes around the daily quotes

Add " around quotes

---

.gitignore
src/plugins/widgets/search/Search.sass
src/plugins/widgets/search/Search.tsx
src/plugins/widgets/search/SearchSettings.tsx
src/plugins/widgets/search/Suggestions.tsx
src/plugins/widgets/search/getSuggestions.ts
src/plugins/widgets/search/interfaces.ts
src/plugins/widgets/search/suggestions/Suggestions.sass
src/plugins/widgets/search/suggestions/Suggestions.tsx
src/plugins/widgets/search/suggestions/getSuggestions.ts
src/plugins/widgets/search/suggestions/index.ts
src/plugins/widgets/search/suggestions/interfaces.ts

Added search suggestions as of #33 
Need help with styling.

Feature Request: Add search suggestions

---

package-lock.json
src/plugins/widgets/register.ts
src/plugins/widgets/reload/Reload.tsx
src/plugins/widgets/reload/ReloadSettings.tsx
src/plugins/widgets/reload/index.ts

The goal of this pull request is to add a function that can automatically reload the page to stop screen burn out. Fixes #119. 
We may need to add a notice under the background section that if you select every 15 minutes, it doesn't refresh every 15 minutes.

Reduce chance of screen burnout

---

src/plugins/backgrounds/unsplash/Unsplash.tsx

There used to be a random 0 in the top left of the screen when darken was all the way down. Fixes #123.

Remove random 0

---

docs/Tabliss_2.md

See pretty version of the planning document: [Tabliss 2 Planning Document](https://github.com/joelshepherd/tabliss/blob/rfc-2/docs/Tabliss_2.md)
I am creating this PR to open up my planning of Tabliss version 2 to anyone who wants to contribute.
So far I have added some of the most requested features that would require a design changes to "Feature Goals". And some of my personal thoughts about the technical implementation in "Technical Goals".
Some questions I am still working on:
- Should you be able to have more than 1 of a single widget?
- Should they share state or not?
- How to implement a flexible widget layout system?
- Snapping grid system
- Draggable absolute (%) positioning
- Layout slots - similar to Apple Watch complications

Goals for Tabliss 2 [Request For Comment]

---

src/locales/lang/zh-TW.json

Improve Traditional Chinese translation

Improve Traditional Chinese translation

---

src/plugins/backgrounds/giphy/GiphySettings.tsx
src/plugins/backgrounds/giphy/api.ts

just a lil something I wanted to have in my own new tab page

[Feature] Allows for picking of gifs from random tags

---

src/plugins/widgets/weather/Weather.tsx
src/plugins/widgets/weather/api.ts
src/plugins/widgets/weather/types.ts

This changes to weather widget to display the daily forecast instead of live conditions and improves its caching.

Changing to daily weather forecast

---

scripts/translations.js
src/locales/lang/lt.json
src/locales/locales.ts
src/views/settings/System.tsx

Adding Lithuanian translation. :)

Lithuanian translation

---

src/locales/lang/ru.json

Update Russian translation

---

src/locales/lang/it.json

Hi, I updated the Italian translation. 
I'm currently trying to complete my Hacktoberfest pull request objective, so, can you add the label hacktoberfest-accepted label to this pull (or add the topic "hacktoberfest" topic to this repository to opt-in all pulls) so that can count towards my objective? Thanks so much for the help.

Updated italian translation

---

src/locales/lang/zh-CN.json

I think there should be no translation mistakes.

i18n:update zh-CN

---

src/plugins/widgets/index.ts
src/plugins/widgets/ipInfo/IpInfo.sass
src/plugins/widgets/ipInfo/IpInfo.tsx
src/plugins/widgets/ipInfo/IpInfoSettings.tsx
src/plugins/widgets/ipInfo/api.ts
src/plugins/widgets/ipInfo/index.ts
src/plugins/widgets/ipInfo/types.ts

This PR adds a widget to display the clients current IP and city/country geo location data.  
I built this for myself but would like to contribute it as I think it's pretty useful and works well.
See a small demonstration of what it does:
https://user-images.githubusercontent.com/9215743/108529572-e412c280-72d4-11eb-9508-91839957b277.mp4
I followed the projects conventions for directory structures, naming and so on.  
Please let me know if you have any questions or concerns!

IP-Info widget

---

src/plugins/widgets/search/engines.ts

[MetaGer is a privacy-oriented meta search.](https://metager.org/about)

Add MetaGer search engine

---

src/locales/lang/fr.json

Hi, 
Just an update to the french translation.

A small update to the "fr" lang.

---

src/plugins/backgrounds/unsplash/Unsplash.tsx
src/plugins/widgets/quote/Quote.sass
src/plugins/widgets/quote/Quote.tsx

[x] When receive long quotes then UI breaks if we are using multiple widgets on screen.
[x] Add a black gradient overlay to background image to make white text more visible on screen. 
Please let me know if you have any questions or suggestions..
#340

long quotes break the UI

---

src/db/action.ts
src/plugins/widgets/weather/LocationInput.tsx
src/plugins/widgets/weather/Weather.tsx
src/plugins/widgets/weather/WeatherSettings.tsx
src/plugins/widgets/weather/api.ts
src/plugins/widgets/weather/conditions.ts
src/plugins/widgets/weather/icons.ts
src/plugins/widgets/weather/types.ts

DarkSky was purchased by Apple, who have deprecated the API access. Migrating to [Open-Meteo](https://open-meteo.com/en).
And now the weather API is no longer costing me thousands per year, I have changed the weather widget back to real time conditions.

Migrating weather API

---

package-lock.json
package.json
src/plugins/widgets/github/GitHub.tsx
src/plugins/widgets/github/GitHubSettings.tsx
src/plugins/widgets/github/github-calendar.css
src/plugins/widgets/github/github-calendar.d.ts
src/plugins/widgets/github/index.ts
src/plugins/widgets/github/types.ts
src/plugins/widgets/index.ts

Close #408
<details>
<summary>Screenshot</summary>
</details>

Add GitHub widget

---

CHANGELOG.md
package-lock.json
package.json
src/plugins/widgets/todo/Todo.tsx

Stops the keyboard shortcut from appearing in the new Todo.
Also bumps `react-intl` to avoid a dependency conflict with React v18.
***Related***
#434

[Todos]: Stop keyboard shortcut appearing in Todo

---

package-lock.json
package.json

Fixes #515 
Signed-off-by: James Hughes <james.hughes@codurance.com>

fix: Updated github-calendar package with upstream skylines fix

---

src/plugins/widgets/search/engines.ts

Fixed Phind search engine

---

src/locales/lang/de.json

Hi!
This is a tiny PR to improve the German translation a bit!
Keep up the great work!
_An_

Improve German translation
