joelshepherd/tabliss

- .gitignore
- public/index.html
- src/plugins/widgets/links/LinkDisplay.tsx
- src/plugins/widgets/links/LinkInput.tsx
- src/plugins/widgets/links/interfaces.ts
This is a PR to resolve feature request #36.
The Link settings has an additional optional field call _Font Awesome Icon_. This field allows the user to specify the Font Awesome icon they wish to use.
When only the _URL_, or when the _URL_ and _Name_ are specified, the application acts as it did before. 
When the _URL_ and _Font Awesome Icon_ are specified, the Font Awesome icon is displayed.
When all three are specified, the Font Awesome icon is displayed to the left of the name.
> Allow a Font Awesome Icon to be Set for Quick Links

- src/plugins/backgrounds/giphy/Giphy.tsx
- src/plugins/widgets/css/Css.sass
- src/plugins/widgets/css/Css.tsx
- src/plugins/widgets/css/CssSettings.tsx
- src/plugins/widgets/css/index.ts
- src/plugins/widgets/register.ts
Added a widget for supplying custom css which would close #40.
As requested, it includes a short message describing its intention for advanced users, and a warning that the custom css could break at any time due to changes within the plugin.
I also included a quick fix that was stopping me from compiling to test.
> Custom CSS

- src/plugins/widgets/js/Js.tsx
- src/plugins/widgets/js/JsSettings.tsx
- src/plugins/widgets/js/index.ts
- src/plugins/widgets/register.ts
I added a new widget for running a bit of JavaScript when opening a new tab. I took the CSS widget as a template.
Due to limitations in the WebExtentions API you can not inject JavaScript into about:newtab. This plugin there for provides a workaround for just that.
The entered JavaScript is run in a non privileged context i.e. can not call add-on API's.
If an event listener is added in the code, it can not really be removed when the code is updated and will be rerun. I suspect that this is not really a problem because this only happens when you edit the code wich will be only a fraction of the time this plugin will be used. To workaround this you can always reload the tab.
I mention this together with a warning like in the CSS plugin under the input box.
> Add JavaScript Widget

- src/plugins/widgets/weather/LocationInput.tsx
I noticed that the Google Maps API doesn't work anymore because it requires an API key, so here is a fix that uses OpenStreetMap instead to geocode location search 🗺
> Use OpenStreetMap Nominatim API to geocode location search

- src/plugins/backgrounds/unsplash/Unsplash.tsx
I tried to add a simple image load check, so when "ERR_FILE_NOT_FOUND" happens then new image will be loaded from Unsplash.
Basically we just check if we are able to load the image with generated url at https://github.com/joelshepherd/tabliss/blob/44f10618552657f4843db861eb2c9f59b9c61912/src/plugins/backgrounds/unsplash/Unsplash.tsx#L115
and if not, then we get new image from Unsplash.
Probably there is a better way to do it: to use already loaded "next" image etc.
> Attempt to fix #78 by adding image load check

- src/locales/lang/sv.json
I accidentally added a space at the end in the translation credit. I was worried that it would cause issues with text formatting so I have removed it. Sorry for the confusion, I'm still learning :)
> Remove extra space in sv.json

- src/views/dashboard/Widgets.sass
- src/views/settings/Widget.tsx
There was a commented out font weight selector. I have bought it back, along with settings all the headings inside of the dash board to `font-weight: inherit`. This should allow the font weight to be overridden. 
Fixes: #210
> Bring back the font weight selector

- src/plugins/widgets/quote/api.ts
This intends to improve the typographical correctness of the Quotes widget, by performing various operations in the `getQuote` function:
- Removing whitespace characters at the beginning and the end of the quote.
- Replacing all non conventional ellipsis by a proper one (…).
- Replacing all improper hyphens by a proper em dash (—).
- Replacing all series of spaces by a single one.
- Replacing all straight quotes (' and ") by curvy ones (‘ and ’), choosing one or the other depending on the previous characters.
- Adding a closing period at the end of the quote if need be.
This is in keeping with proper typographical rules, as one can find in [the key rules](https://practicaltypography.com/summary-of-key-rules.html) from _Butterick’s Practical Typography_ book.
This makes extensive use of …
> Better typography for quotes

- CHANGELOG.md
- src/plugins/widgets/time/Digital.tsx
- src/plugins/widgets/time/IntlTime.tsx
**tl;dr** 
Chrom(ium) did a thing. React-intl didn't implement the thing I need to do to fix the thing.
**Detailed description**
Somewhere around chrome 80 `hourCycle` was added as a property in the config for `Intl.DateTimeFromat()`. `hourCycle` defaults to `h24` that goes from `01:XX` - `24:XX` rather than `h23` that goes from `00:XX` - `23:XX`. React-intl doesn't [appear to have added that change to their library as of yet](https://github.com/formatjs/react-intl/issues/1577). This commit has a custom implementation of `Intl.DateTimeFromat().format()` to bypass this issue. This issue should also prevent breakages in the future as other browsers at this feature. 
At some point `react-intl` will allow this to be cofigured in their library and this pull request can be reverted, with the …
> Fix issues with react-intl and time

- CHANGELOG.md
- src/plugins/widgets/time/Digital.tsx
- src/plugins/widgets/time/IntlTime.tsx
- src/plugins/widgets/time/Time.tsx
- src/plugins/widgets/time/TimeSettings.tsx
- src/plugins/widgets/time/types.ts
This pull request adds a checkbox that allows you to toggle the display of `AM` / `PM`. Possible implementations were discussed in #247. 
Fixes #247.
> Add toggle for day period

- CHANGELOG.md
- src/hooks/useKeyPress.ts
Prior to this commit, tabliss responded to keystrokes meant for the browser or system. One example of this is if you used alt (or meta on mac) + a number to switch tabs, you would trigger tabliss to open a quick link at the same time. This pull request stops tabliss from registering key strokes when the meta, control or alt keys are pressed. 
Fixes #235.
> Ignore system keystrokes

- src/plugins/widgets/links/Display.tsx
- src/plugins/widgets/links/Links.tsx
- src/plugins/widgets/links/LinksSettings.tsx
- src/plugins/widgets/links/types.ts
This pull request adds a checkbox that allows you to toggle the opening of links in a new tab. 
Fixes #263.
> Add open links in new tab option.

- src/plugins/backgrounds/unsplash/api.ts
* refactored fetching of image from ImgIX to be deligated to a seperate function, use URLSearchParams to specify parameters instead of hardcoded query
* dynamically decide width of image according to size of screen with max size of 8192 set by Unsplash Images
> refactor image fetch from ImgIX, decide width according to screen

- src/plugins/widgets/links/Display.tsx
- src/plugins/widgets/links/Links.sass
This fixes a small but annoying cosmetical issue with the "Quick Links" feature.
If an icon **and** a link name (or URL) are displayed in a link, theres a leading whitespace in front of the text for separating the icon from the text. On hover, the complete link text (including the whitespace) is underlined, which is rather unpleasant to the eye:
What this tiny PR does is the following - it looks much less glitchy:
I hope this is not too negligible to fix.  
Thank you for this useful extension!
> Fix underline leading space in link text on hover

- src/plugins/widgets/time/TimeSettings.tsx
The "Analogue" label for the radio button in the Time widget settings was not clickable
> Fix incorrectly nested label

- src/plugins/widgets/links/Links.tsx
minor change so that open link in new tab option is applied to both keyboard shortcuts and onClick
> open links in new tab by keyboard

- src/views/dashboard/Dashboard.tsx
If a widget is placed on top of the screen, it can cover and make the configuration button over not clickable due to the z-index order.
Update the template and move `<Overlay>` to appear after `<Widgets>`, which solves the z-index problems without CSS changes, and also makes the overlay in a more semantic order.
> Move <Overlay> after <Widgets>

- src/plugins/backgrounds/unsplash/UnsplashCredit.tsx
I have an Unsplash account that I use to "Like" images, and if I like the image in a new tab, I do the following:
1. I've just pressed Cmd-T (or Ctrl-T) to open a new tab, which is displaying Tabliss.
2. I want to "Like" the image, so I click [the link in the bottom left](https://github.com/joelshepherd/tabliss/blob/4bad66431d32fa30dfa13e835206af4dd82e7b7e/src/plugins/backgrounds/unsplash/UnsplashCredit.tsx#L15-L25).
3. I don't want to lose my previous train of thought, though, so I immediately press Cmd-T to open another new tab and continue what I was doing (so I can come back to the Unsplash page later).
4. There is now an empty Tabliss tab open in the background in addition to the Unsplash tab.
Basically the problem with opening the Unsplash page in a new tab is that if you're opening …
> Open Unsplash Page in Current Window

- src/views/settings/Settings.tsx
The current dev build fails due to a prior commit not removing the associated imports for settings. This should fix it.
> Remove feedback import from settings

- src/plugins/backgrounds/giphy/api.ts
Giphy changed the way the data in the object is sent. Modified the path to get the original image URL to the correct one in the new Object.
> Fixed issue with Giphy not loading images

- src/views/settings/System.tsx
The label for the german language is spelled with a capital H at the end:
This PR corrects this to:
> Fix label for german language in language selector

- src/plugins/widgets/links/Links.tsx
When you set the "columns" parameter to a value greater than 1, the button used to display the links no longer shifts to the left and remains centered
Before : 
After :
> Update Links.tsx -> fix button shift when columns > 1
